config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  resources :tasks

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, :description, :deadline, presence: true
  validates :name, uniqueness: { scope: :user }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @tasks = current_user.tasks
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    redirect_to dashboard_url if signed_in?
  end


  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    # @task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to dashboard_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :deadline, :done, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboards/show.html.erb
<div class="container-center">
  <h2 class="page-title" >Welcome <%= current_user.username.capitalize %>! </h2>
  <div class="task-container">
    <h1>Tasks</h1>

    <table class="table table-hover table-borderless">
      <thead>
        <tr>
          <th>Status</th>
          <th>Name</th>
          <th>Description</th>
          <th>Deadline</th>
          <th>Done</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <% if task.user == current_user %>
            <% if task.done %>
              <tr>
                <td><%= task.done ? '✅' : '❌'  %></td>
                <td><%= task.name %></td>
                <td><%= task.description %></td>
                <td><%= task.deadline.strftime("%d/%m/%Y") %></td>
                <td>
                  <%= form_for(task) do |f| %>
                  <%= f.check_box :done, :checked => false, :style => 'visibility: hidden' %>
                  <%= f.submit 'Cross', class: 'btn btn-sm', id: 'btn-check' %>
                  <% end %>
                </td>
                <td><%= link_to '🗑', task, method: :delete, data: { confirm: 'Silmek istediğinize emin misiniz?' }, class: 'btn btn-sm' %></td>
              </tr>
            <% else %>
              <tr>
                <td><%= task.done ? '✅' : '❌'  %></td>
                <td><%= task.name %></td>
                <td><%= task.description %></td>
                <td><%= task.deadline.strftime("%d/%m/%Y") %></td>
                <td>
                  <%= form_for(task) do |f| %>
                  <%= f.check_box :done, :checked => true, :style => 'visibility: hidden' %>
                  <%= f.submit 'Check', class: 'btn btn-sm', id: 'btn-check' %>
                  <% end %>
                </td>
                <td><%= link_to '🗑', task, method: :delete, data: { confirm: 'Silmek istediğinize emin misiniz?' }, class: 'btn btn-sm' %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Task', new_task_path, class:'btn btn-sm', id: 'btn-check' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-center">
  <h1 class="page-title">Welcome to myTime <%= current_user.username.capitalize %> </h1>
  <p>Start to manage your time and reach your goals!</p>

  <%= link_to 'New Task', new_task_path, class:'btn btn-sm', id: 'btn-check' %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show notice-color" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pangolin&family=Roboto:ital@1&display=swap" rel="stylesheet">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'tasks/header' %>
    <div class="container">
    <br>
      <% if notice %>
        <%= notice %>
      <% end %>

      <%= yield %>
    </div>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "hata") %> var görev kaydedilemedi</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li class="list-group-item list-group-item-warning"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: 'task name', class: "form-box" %>
  </div>

  <div class="field">
    <%= form.text_field :description, placeholder: 'task description', class: "form-box" %>
  </div>

  <div class="field">
    <%= form.date_select :deadline %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: :hidden, class: "form-box" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:'btn btn-sm', id:'btn-check' %>
  </div>
<% end %>

app/views/tasks/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to 'myTime App', root_path, class:'navbar-brand', id:'navbar-title' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation" id="toggle-style" >
    <span class="navbar-toggler-icon" id="toggle-style"  ></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto ">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link', id:'navbar-title' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link', id:'navbar-title' %>
        </li>
        <li class="nav-item">
          <%= link_to 'myTime', dashboard_path, class:'nav-link', id:'navbar-title' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:'nav-link', id:'navbar-title' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link', id:'navbar-title' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/tasks/edit.html.erb
<div class='container-new'>
  <h1>Editing Task</h1>

  <%= render 'form', task: @task %>

  <%= link_to 'Show', @task %> |
  <%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="task-container">
  <h1>Tasks</h1>

  <table class="table table-hover table-borderless">
    <thead>
      <tr>
        <th>Status</th>
        <th>Name</th>
        <th>Description</th>
        <th>Deadline</th>
        <th>Done</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <% if task.done %>
          <tr>
            <td><%= task.done ? '✅' : '❌'  %></td>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= task.deadline.strftime("%d/%m/%Y") %></td>
            <td>
              <%= form_for(task) do |f| %>
              <%= f.check_box :done, :checked => false, :style => 'visibility: hidden' %>
              <%= f.submit 'Cross', class: 'btn btn-sm', id: 'btn-check' %>
              <% end %>
            </td>
            <td><%= link_to '🗑', task, method: :delete, data: { confirm: 'Silmek istediğinize emin misiniz?' }, class: 'btn btn-sm' %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= task.done ? '✅' : '❌'  %></td>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= task.deadline.strftime("%d/%m/%Y") %></td>
            <td>
              <%= form_for(task) do |f| %>
              <%= f.check_box :done, :checked => true, :style => 'visibility: hidden' %>
              <%= f.submit 'Check', class: 'btn btn-sm', id: 'btn-check' %>
              <% end %>
            </td>
            <td><%= link_to '🗑', task, method: :delete, data: { confirm: 'Silmek istediğinize emin misiniz?' }, class: 'btn btn-sm' %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Task', new_task_path, class:'btn btn-info btn-sm' %>
</div>

app/views/tasks/new.html.erb
<div class='container-new'>
  <h1 class="page-title">New Task</h1>

  <%= render 'form', task: @task %>
  <br>

  <%= link_to 'Back', dashboard_path, class:'btn', id: 'btn-cross' %>
</div>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done ? '✅' : '❌' %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', dashboard_path %>